baseurl = "/"
title = "补漏砖匠"
languageCode = "en-us"
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[pagination]
  pagerSize = 5 # Number of posts per page
[Params.style.vars]
  highlightColor = "#3498db"
[Params]
  subtitle = "独钓寒江雪，为有暗香来。" # Subtitle of your site. Used in site header
  description = "Wu guo jun Personal blog about everything" # Site description. Used in meta description
  #copyright = "John Doe" # copyright holder, otherwise will use site title
  #opengraph = false # Enable OpenGraph if true
  #twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories"] # Order of post meta information. Use ["none"] to turn off completely.
  postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
  #postSections = ["blog", "news"] # alternative that shows more than one section's pages
  #dateformat = "2006-01-02" # change the format of dates
  #mathjax = true # Enable MathJax
  #mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" # Specify MathJax path
  #mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
[Params.author] # Used in authorbox
  name = "wu guojun"
  bio = "。"
  avatar = "img/blowizer.png"

[Params.sidebar]
  home = "left" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  #facebook = "username"
  #twitter = "username"
  #instagram = "username"
  #linkedin = "username"
  #telegram = "username"
  github = "blowizer"
  #gitlab = "username"
  #bitbucket = "username"
  email = "blowizer@qq.com"
  #google_plus = "profileid"
